---
- name: Ensure required packages are installed.
  ansible.builtin.apt:
    name:
      - rsync
      - cron
      - sshpass
    state: present

- name: Ensure password file for rsync user exists.
  ansible.builtin.copy:
    content: "{{ rsync_user_password }}"
    dest: "{{ rsync_user_passfile }}"
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: 0600
  when: rsync_user_password is defined

- name: Ensure backup folder exists.
  ansible.builtin.file:
    path: "{{ backup_path }}"
    state: directory
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: 0775

- name: Copy backup script to server.
  ansible.builtin.template:
    src: backup.sh.j2
    dest: "{{ backup_path }}/backup.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: 0744

- name: Copy excludes file to server.
  ansible.builtin.template:
    src: backup-exclude.txt.j2
    dest: "{{ backup_path }}/backup-exclude.txt"
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: 0644

- name: Configure backup cron job.
  ansible.builtin.cron:
    name: "Backup cron job"
    weekday: "{{ backup_dow }}"
    minute: "{{ backup_minute }}"
    hour: "{{ backup_hour }}"
    user: "{{ backup_user }}"
    job: "{{ backup_path }}/backup.sh"
    state: "{{ backup_cron_job_state }}"

- name: Add backup remote host key to server.
  ansible.builtin.known_hosts:
    path: "/etc/ssh/ssh_known_hosts"
    name: "{{ backup_remote_host_name }}"
    key: "{{ backup_remote_host_name }} {{ backup_remote_host_key }}"
  when:
    - backup_remote_host_name
    - backup_remote_host_key

- name: Include database backup tasks.
  ansible.builtin.include_tasks: databases.yml
  when: backup_mysql | bool
